# Generated by Django 3.0.3 on 2020-04-09 10:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20200407_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
