# Generated by Django 3.0.3 on 2020-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('New', 'Yeni'), ('False', 'Hayır')], default='New', max_length=10),
        ),
    ]
