# Generated by Django 3.0.3 on 2020-05-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_auto_20200512_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('False', 'Hayır'), ('True', 'Evet')], default='New', max_length=10),
        ),
    ]
