# Generated by Django 3.0.3 on 2020-05-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_auto_20200514_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
