# Generated by Django 3.0.3 on 2020-05-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_reservationvehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
