# Generated by Django 3.0.3 on 2020-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200605_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationvehicle',
            name='date',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
